### PR TITLE
Digitizer mc

### PR DESCRIPTION
**Pull request by mwinn2**
TEST
Introduction of MClabels
still todo: provide proper test to check that it is working, DPL interface of MCtruth labels probably to be modified
first prototype of testing of Response
still todo: rewrite CMakeLists.txt in test directory such that compilation works together for GeometryTest and ResponseTest

### CODE REVIEW

**Comment by mwinn2** [comment]
@aphecetche: is this what you had in mind as workflow for the discussion 
(I left in the debugging comments, I just wanted to check, if this is correct)
I also didn't find where to squash the commits... in the webinterface, this is not very handy

**Comment by mwinn2** [comment]
@aphecetche :  Would be in particular nice to have the same tests in the central repository, but also not a big deal not to have it.

**Comment by aphecetche** [comment]
@mwinn2 yes, this is what I had in mind (ok, with a local rebase before the PR maybe ;-) but that's ok)

**Comment by aphecetche** [comment]
> @aphecetche : Would be in particular nice to have the same tests in the central repository, but also not a big deal not to have it.

If we want the CI then we'd have to make the PR to the upstream repo, indeed. I guess to discuss the code, this is fine for now.

**Pull request closed without merging**
